-- ============================================================
-- Kurasel データベース初期化スクリプト
-- Supabase ダッシュボードの SQL Editor に貼り付けて実行してください。
-- 何度実行しても壊れないように書いてあります。
-- ============================================================

-- ------------------------------------------------------------
-- 0. 世帯（ふたりの家計）とメンバー
-- ログインは Supabase Auth の Google ログイン。誰と誰がペアかは Google からは分からないので、
-- 「世帯」を作り、招待コードで相手を同じ世帯に入れる。1人が入れる世帯は1つ、1世帯は2人まで。
-- ふたりの記録は household_id、個人の記録は owner（ログインユーザーのID）で持ち主を決める
-- ------------------------------------------------------------
create table if not exists public.households (
  id uuid primary key default gen_random_uuid(),
  invite_code text unique,              -- 招待コード。参加されたら消す（1回だけ使える）
  invite_expires_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.household_members (
  user_id uuid primary key references auth.users (id) on delete cascade, -- 主キーなので1人1世帯
  household_id uuid not null references public.households (id) on delete cascade,
  display_name text not null,
  joined_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists household_members_household_id_idx
  on public.household_members (household_id);

-- ログイン中の人の世帯。RLS と列の既定値で使う。
-- household_members の RLS からこの関数を呼ぶので、RLS を通さない security definer にしている
create or replace function public.my_household_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select household_id from public.household_members where user_id = auth.uid()
$$;

-- 世帯を作って自分がメンバーになる
create or replace function public.create_household(display_name text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  new_id uuid;
begin
  if auth.uid() is null then raise exception 'not_signed_in'; end if;
  if exists (select 1 from household_members where user_id = auth.uid()) then raise exception 'already_member'; end if;
  if coalesce(trim(display_name), '') = '' then raise exception 'name_required'; end if;

  insert into households default values returning id into new_id;
  insert into household_members (user_id, household_id, display_name) values (auth.uid(), new_id, trim(display_name));
  return new_id;
end;
$$;

-- 相手に送る招待コードを発行する（24時間有効）。前のコードは使えなくなる
create or replace function public.create_invite()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  hid uuid := public.my_household_id();
  code text;
begin
  if hid is null then raise exception 'no_household'; end if;
  if (select count(*) from household_members where household_id = hid) >= 2 then raise exception 'household_full'; end if;

  -- 推測されないよう、乱数は gen_random_uuid()（暗号論的な乱数）から取る。
  -- 各バイトの下位5ビットはどれも乱数なので、32文字から1文字を偏りなく選べる。
  -- 読み間違えやすい 0/O・1/I は使わない
  select string_agg(substr('ABCDEFGHJKLMNPQRSTUVWXYZ23456789', 1 + get_byte(b, i) % 32, 1), '' order by i)
    into code from (select uuid_send(gen_random_uuid()) as b) r, generate_series(0, 7) i;
  update households set invite_code = code, invite_expires_at = now() + interval '24 hours' where id = hid;
  return code;
end;
$$;

-- 招待コードで相手の世帯に入る。参加されたらコードは消す
create or replace function public.join_household(code text, display_name text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  hid uuid;
begin
  if auth.uid() is null then raise exception 'not_signed_in'; end if;
  if exists (select 1 from household_members where user_id = auth.uid()) then raise exception 'already_member'; end if;
  if coalesce(trim(display_name), '') = '' then raise exception 'name_required'; end if;

  -- 同時に2人が同じコードで入らないよう、世帯の行を押さえてから数える
  select id into hid from households
    where invite_code = upper(trim(code)) and invite_expires_at > now()
    for update;
  if hid is null then raise exception 'invalid_invite'; end if;
  if (select count(*) from household_members where household_id = hid) >= 2 then raise exception 'household_full'; end if;

  insert into household_members (user_id, household_id, display_name) values (auth.uid(), hid, trim(display_name));
  update households set invite_code = null, invite_expires_at = null where id = hid;
  return hid;
end;
$$;

revoke all on function public.create_household(text) from public, anon;
revoke all on function public.create_invite() from public, anon;
revoke all on function public.join_household(text, text) from public, anon;
grant execute on function public.create_household(text) to authenticated;
grant execute on function public.create_invite() to authenticated;
grant execute on function public.join_household(text, text) to authenticated;

-- ------------------------------------------------------------
-- 1. ユーザー（旧）
-- Google ログインにする前の、名前だけのユーザー。今のアプリは使わない。
-- 以前のデータを引き継ぐとき（supabase/migrate_legacy.sql）に名前の対応だけ見る
-- ------------------------------------------------------------
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ------------------------------------------------------------
-- 2. 支出記録
-- ------------------------------------------------------------
create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  store_name text,
  amount integer,
  purchase_date date,
  paid_by text,
  category text,
  reactions jsonb default '{}'::jsonb,
  comments jsonb default '[]'::jsonb,
  receipt_url text,
  group_id bigint -- 現状どこからも使われていない。既存テーブルに合わせて残してある
);

-- おごり等。記録は残すが割り勘には入れない。
-- 既存のテーブルにも足せるよう create table とは別に書いている
alter table public.expenses
  add column if not exists is_excluded boolean default false not null;

-- 精算済みの印。途中まで精算したとき、済んだ記録を精算額の計算から外す
alter table public.expenses
  add column if not exists is_settled boolean default false not null;

-- 精算画面は「月初〜月末」で絞り込むのでインデックスを張る
create index if not exists expenses_purchase_date_idx
  on public.expenses (purchase_date desc);

-- ------------------------------------------------------------
-- 3. 月次精算ステータス
-- ------------------------------------------------------------
create table if not exists public.monthly_settlements (
  month text primary key,              -- 'YYYY-MM'
  is_paid boolean default false,
  is_received boolean default false,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- ------------------------------------------------------------
-- 4. 旅行
-- 日常の支出・月次精算と混ざらないよう、テーブルごと分けている。
-- 精算ステータスも旅行単位で持つ。
-- ------------------------------------------------------------
create table if not exists public.trips (
  id bigint generated by default as identity primary key,
  name text not null,
  start_date date,
  end_date date,
  is_paid boolean default false,
  is_received boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 旅行の予算（目標利用金額）。null なら未設定。
-- 比べる「使った額」は、おごり・精算済みも含めた旅行中の支出すべて
alter table public.trips
  add column if not exists budget integer;

create table if not exists public.trip_expenses (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips (id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  store_name text,
  amount integer,
  purchase_date date,
  paid_by text,
  category text,
  receipt_url text,
  is_excluded boolean default false not null -- おごり等。記録は残すが割り勘には入れない
);

-- 精算済みの印。途中まで精算したとき、済んだ記録を精算額の計算から外す
alter table public.trip_expenses
  add column if not exists is_settled boolean default false not null;

create index if not exists trip_expenses_trip_id_idx
  on public.trip_expenses (trip_id);

-- ------------------------------------------------------------
-- 5. 個人の支出
-- ふたりの家計・精算とは混ざらないよう、テーブルごと分けている。
-- owner（users.name）が自分の記録だけを画面に出す。
-- ただしこのアプリには本当の認証がないので、DB上は相手からも読める（下の RLS の説明を参照）。
-- ------------------------------------------------------------
create table if not exists public.personal_expenses (
  id bigint generated by default as identity primary key,
  owner text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  store_name text,
  amount integer,
  purchase_date date,
  category text,
  receipt_url text
);

create index if not exists personal_expenses_owner_date_idx
  on public.personal_expenses (owner, purchase_date desc);

-- ------------------------------------------------------------
-- 5-2. サブスク（個人）
-- 支払日が来たら、アプリを開いたときに personal_expenses へ自動で記録する。
-- billing_day は最初の支払日の「日」。31日払いが2月に29日などへずれても、翌月は31日に戻すために持つ
-- ------------------------------------------------------------
create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  owner text not null,
  name text not null,
  amount integer not null,
  cycle text not null default 'monthly' check (cycle in ('monthly', 'yearly')),
  billing_day integer not null check (billing_day between 1 and 31),
  next_billing_date date not null,
  category text,
  is_active boolean default true not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists subscriptions_owner_idx
  on public.subscriptions (owner);

-- 自動で記録した支出が、どのサブスクのものか。サブスクを消しても記録は残す
alter table public.personal_expenses
  add column if not exists subscription_id bigint references public.subscriptions (id) on delete set null;

-- 同じサブスクの同じ支払日は1回だけ記録する（2台で同時に開いても二重にならないように）
create unique index if not exists personal_expenses_subscription_date_key
  on public.personal_expenses (subscription_id, purchase_date)
  where subscription_id is not null;

-- ------------------------------------------------------------
-- 5-2-2. 収入
-- 個人の収入（給料など。本人だけが見られる）と、ふたりの収入（給付金・お祝いなど。世帯のふたりが見られる）を
-- 1つのテーブルで持ち、is_shared で分ける。精算には使わない（分析で収支を見るため）。
-- owner は記録した人のID（auth.users.id）。世帯・記録した人は既定値で入るので、アプリからは渡さない
-- ------------------------------------------------------------
create table if not exists public.incomes (
  id bigint generated by default as identity primary key,
  household_id uuid not null default public.my_household_id() references public.households (id) on delete cascade,
  owner text not null default (auth.uid())::text,
  is_shared boolean not null default false,
  source text,                          -- 内容（勤務先・「定額給付金」など）
  amount integer not null check (amount > 0),
  received_date date not null,
  category text,                        -- app/lib/income.ts の INCOME_CATEGORIES の id
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists incomes_household_date_idx
  on public.incomes (household_id, received_date desc);

-- ------------------------------------------------------------
-- 5-3. 持ち主の列
-- ふたりの記録（日常・月次精算・旅行）は household_id で世帯に属する。
-- 旅行の記録（trip_expenses）は旅行を通して世帯に属するので列は持たない。
-- 既定値を my_household_id() にしているので、アプリは household_id を渡さずに追加できる。
--
-- paid_by・owner・reactions のキー・comments の user は、以前は名前（users.name）を入れていた。
-- 今はログインユーザーのID（auth.users.id）を文字列で入れる。名前は household_members.display_name から引く。
-- 型を text のままにしているのは、以前のデータを引き継ぐまで名前とIDが混ざるため
-- ------------------------------------------------------------
alter table public.expenses
  add column if not exists household_id uuid references public.households (id) on delete cascade;
alter table public.monthly_settlements
  add column if not exists household_id uuid references public.households (id) on delete cascade;
alter table public.trips
  add column if not exists household_id uuid references public.households (id) on delete cascade;

alter table public.expenses alter column household_id set default public.my_household_id();
alter table public.monthly_settlements alter column household_id set default public.my_household_id();
alter table public.trips alter column household_id set default public.my_household_id();
alter table public.personal_expenses alter column owner set default (auth.uid())::text;
alter table public.subscriptions alter column owner set default (auth.uid())::text;

create index if not exists expenses_household_date_idx
  on public.expenses (household_id, purchase_date desc);
create index if not exists trips_household_id_idx
  on public.trips (household_id);

-- 月次精算は「世帯 × 月」で1行。以前は月だけが主キーだった
alter table public.monthly_settlements drop constraint if exists monthly_settlements_pkey;
create unique index if not exists monthly_settlements_household_month_key
  on public.monthly_settlements (household_id, month);

-- ------------------------------------------------------------
-- 6. アクセス制御 (RLS)
--
-- ログインした人（authenticated）だけが読み書きできる。
--   ふたりの記録: 同じ世帯のメンバーだけ
--   個人の記録: 本人だけ（相手からも見えない）
-- ログインしていない anon には何も許可しない（デモモードはDBに触れない）。
-- 世帯を作る・招待する・参加するは、上の関数を通してだけ行う
-- ------------------------------------------------------------
alter table public.households enable row level security;
alter table public.household_members enable row level security;
alter table public.users enable row level security;
alter table public.expenses enable row level security;
alter table public.monthly_settlements enable row level security;
alter table public.trips enable row level security;
alter table public.trip_expenses enable row level security;
alter table public.personal_expenses enable row level security;
alter table public.subscriptions enable row level security;
alter table public.incomes enable row level security;

-- 以前の「誰でも読み書きできる」ポリシーを外す
drop policy if exists "anon full access" on public.users;
drop policy if exists "anon full access" on public.expenses;
drop policy if exists "anon full access" on public.monthly_settlements;
drop policy if exists "anon full access" on public.trips;
drop policy if exists "anon full access" on public.trip_expenses;
drop policy if exists "anon full access" on public.personal_expenses;
drop policy if exists "anon full access" on public.subscriptions;

drop policy if exists "members read" on public.households;
create policy "members read" on public.households
  for select to authenticated using (id = public.my_household_id());

drop policy if exists "members read" on public.household_members;
create policy "members read" on public.household_members
  for select to authenticated using (household_id = public.my_household_id());

-- 自分の表示名だけ変えられる（世帯の付け替えは列の権限で防ぐ）
drop policy if exists "update own name" on public.household_members;
create policy "update own name" on public.household_members
  for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
revoke insert, update, delete on public.household_members from anon, authenticated;
grant update (display_name) on public.household_members to authenticated;

drop policy if exists "household members" on public.expenses;
create policy "household members" on public.expenses
  for all to authenticated
  using (household_id = public.my_household_id())
  with check (household_id = public.my_household_id());

drop policy if exists "household members" on public.monthly_settlements;
create policy "household members" on public.monthly_settlements
  for all to authenticated
  using (household_id = public.my_household_id())
  with check (household_id = public.my_household_id());

drop policy if exists "household members" on public.trips;
create policy "household members" on public.trips
  for all to authenticated
  using (household_id = public.my_household_id())
  with check (household_id = public.my_household_id());

drop policy if exists "household members" on public.trip_expenses;
create policy "household members" on public.trip_expenses
  for all to authenticated
  using (exists (select 1 from public.trips t where t.id = trip_id and t.household_id = public.my_household_id()))
  with check (exists (select 1 from public.trips t where t.id = trip_id and t.household_id = public.my_household_id()));

drop policy if exists "owner only" on public.personal_expenses;
create policy "owner only" on public.personal_expenses
  for all to authenticated
  using (owner = (auth.uid())::text)
  with check (owner = (auth.uid())::text);

drop policy if exists "owner only" on public.subscriptions;
create policy "owner only" on public.subscriptions
  for all to authenticated
  using (owner = (auth.uid())::text)
  with check (owner = (auth.uid())::text);

-- 収入: ふたりの収入は世帯のふたりが、個人の収入は本人だけが読み書きできる。
-- 相手の名前で個人の収入を作ることはできない（is_shared でなければ owner は自分）
drop policy if exists "shared or own" on public.incomes;
create policy "shared or own" on public.incomes
  for all to authenticated
  using (household_id = public.my_household_id() and (is_shared or owner = (auth.uid())::text))
  with check (household_id = public.my_household_id() and (is_shared or owner = (auth.uid())::text));

-- ------------------------------------------------------------
-- 7. レシート画像用ストレージ
-- ダッシュボードで手作業で作っても同じ。こちらのほうが取りこぼしがない。
-- 画像は「世帯のID/ファイル名」に置き、同じ世帯のメンバーだけが追加・削除できる。
-- 表示は公開URL（推測できないファイル名）で行うので、一覧の読み取りは許可しない。
-- Google ログイン以前の画像はフォルダなしで置かれていて、アプリからは消せない（表示はできる）
-- ------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('receipts', 'receipts', true)
on conflict (id) do update set public = true;

drop policy if exists "receipts anon read" on storage.objects;
drop policy if exists "receipts anon upload" on storage.objects;
drop policy if exists "receipts anon delete" on storage.objects;

drop policy if exists "receipts household upload" on storage.objects;
create policy "receipts household upload" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'receipts' and (storage.foldername(name))[1] = (public.my_household_id())::text);

drop policy if exists "receipts household delete" on storage.objects;
create policy "receipts household delete" on storage.objects
  for delete to authenticated
  using (bucket_id = 'receipts' and (storage.foldername(name))[1] = (public.my_household_id())::text);

-- 削除の前に対象を探すため、自分の世帯のフォルダだけは読める
drop policy if exists "receipts household read" on storage.objects;
create policy "receipts household read" on storage.objects
  for select to authenticated
  using (bucket_id = 'receipts' and (storage.foldername(name))[1] = (public.my_household_id())::text);

-- ------------------------------------------------------------
-- 8. 分類の統一（2026-09）
-- ふたり・旅行・個人で別々だった分類を1つにまとめた（app/lib/categories.ts）。
-- 個人・旅行の「食事」は「外食」、旅行の「観光」は「趣味・レジャー」へ付け替える。
-- アプリ側でも読み替えているので、実行前でも表示は崩れない。何度実行しても同じ結果になる
-- ------------------------------------------------------------
update public.personal_expenses set category = 'eatout' where category = 'meal';
update public.trip_expenses set category = 'eatout' where category = 'meal';
update public.trip_expenses set category = 'hobby' where category = 'sightseeing';
update public.subscriptions set category = 'eatout' where category = 'meal';
