-- ============================================================
-- Kurasel データベース初期化スクリプト
-- Supabase ダッシュボードの SQL Editor に貼り付けて実行してください。
-- 何度実行しても壊れないように書いてあります。
-- ============================================================

-- ------------------------------------------------------------
-- 1. ユーザー
-- ------------------------------------------------------------
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ------------------------------------------------------------
-- 2. 支出記録
-- ------------------------------------------------------------
create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  store_name text,
  amount integer,
  purchase_date date,
  paid_by text,
  category text,
  reactions jsonb default '{}'::jsonb,
  comments jsonb default '[]'::jsonb,
  receipt_url text,
  group_id bigint -- 現状どこからも使われていない。既存テーブルに合わせて残してある
);

-- 精算画面は「月初〜月末」で絞り込むのでインデックスを張る
create index if not exists expenses_purchase_date_idx
  on public.expenses (purchase_date desc);

-- ------------------------------------------------------------
-- 3. 月次精算ステータス
-- ------------------------------------------------------------
create table if not exists public.monthly_settlements (
  month text primary key,              -- 'YYYY-MM'
  is_paid boolean default false,
  is_received boolean default false,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- ------------------------------------------------------------
-- 4. アクセス制御 (RLS)
--
-- このアプリは Supabase Auth を使わず、ブラウザから anon キーで
-- 直接アクセスする。したがって anon に全操作を許可する必要がある。
-- 裏を返すと、URL と anon キーを知っている人は誰でも読み書きできる。
-- ログイン画面の合言葉は画面を出し分けているだけで、防御にはならない。
-- 将来この前提を変えるときは、ここのポリシーを絞り込む。
-- ------------------------------------------------------------
alter table public.users enable row level security;
alter table public.expenses enable row level security;
alter table public.monthly_settlements enable row level security;

drop policy if exists "anon full access" on public.users;
create policy "anon full access" on public.users
  for all to anon using (true) with check (true);

drop policy if exists "anon full access" on public.expenses;
create policy "anon full access" on public.expenses
  for all to anon using (true) with check (true);

drop policy if exists "anon full access" on public.monthly_settlements;
create policy "anon full access" on public.monthly_settlements
  for all to anon using (true) with check (true);

-- ------------------------------------------------------------
-- 5. レシート画像用ストレージ
-- ダッシュボードで手作業で作っても同じ。こちらのほうが取りこぼしがない。
-- ------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('receipts', 'receipts', true)
on conflict (id) do update set public = true;

drop policy if exists "receipts anon read" on storage.objects;
create policy "receipts anon read" on storage.objects
  for select to anon using (bucket_id = 'receipts');

drop policy if exists "receipts anon upload" on storage.objects;
create policy "receipts anon upload" on storage.objects
  for insert to anon with check (bucket_id = 'receipts');

drop policy if exists "receipts anon delete" on storage.objects;
create policy "receipts anon delete" on storage.objects
  for delete to anon using (bucket_id = 'receipts');
