-- ============================================================
-- Kurasel データベース初期化スクリプト
-- Supabase ダッシュボードの SQL Editor に貼り付けて実行してください。
-- 何度実行しても壊れないように書いてあります。
-- ============================================================

-- ------------------------------------------------------------
-- 1. ユーザー
-- ------------------------------------------------------------
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ------------------------------------------------------------
-- 2. 支出記録
-- ------------------------------------------------------------
create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  store_name text,
  amount integer,
  purchase_date date,
  paid_by text,
  category text,
  reactions jsonb default '{}'::jsonb,
  comments jsonb default '[]'::jsonb,
  receipt_url text,
  group_id bigint -- 現状どこからも使われていない。既存テーブルに合わせて残してある
);

-- おごり等。記録は残すが割り勘には入れない。
-- 既存のテーブルにも足せるよう create table とは別に書いている
alter table public.expenses
  add column if not exists is_excluded boolean default false not null;

-- 精算済みの印。途中まで精算したとき、済んだ記録を精算額の計算から外す
alter table public.expenses
  add column if not exists is_settled boolean default false not null;

-- 精算画面は「月初〜月末」で絞り込むのでインデックスを張る
create index if not exists expenses_purchase_date_idx
  on public.expenses (purchase_date desc);

-- ------------------------------------------------------------
-- 3. 月次精算ステータス
-- ------------------------------------------------------------
create table if not exists public.monthly_settlements (
  month text primary key,              -- 'YYYY-MM'
  is_paid boolean default false,
  is_received boolean default false,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- ------------------------------------------------------------
-- 4. 旅行
-- 日常の支出・月次精算と混ざらないよう、テーブルごと分けている。
-- 精算ステータスも旅行単位で持つ。
-- ------------------------------------------------------------
create table if not exists public.trips (
  id bigint generated by default as identity primary key,
  name text not null,
  start_date date,
  end_date date,
  is_paid boolean default false,
  is_received boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 旅行の予算（目標利用金額）。null なら未設定。
-- 比べる「使った額」は、おごり・精算済みも含めた旅行中の支出すべて
alter table public.trips
  add column if not exists budget integer;

create table if not exists public.trip_expenses (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips (id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  store_name text,
  amount integer,
  purchase_date date,
  paid_by text,
  category text,
  receipt_url text,
  is_excluded boolean default false not null -- おごり等。記録は残すが割り勘には入れない
);

-- 精算済みの印。途中まで精算したとき、済んだ記録を精算額の計算から外す
alter table public.trip_expenses
  add column if not exists is_settled boolean default false not null;

create index if not exists trip_expenses_trip_id_idx
  on public.trip_expenses (trip_id);

-- ------------------------------------------------------------
-- 5. 個人の支出
-- ふたりの家計・精算とは混ざらないよう、テーブルごと分けている。
-- owner（users.name）が自分の記録だけを画面に出す。
-- ただしこのアプリには本当の認証がないので、DB上は相手からも読める（下の RLS の説明を参照）。
-- ------------------------------------------------------------
create table if not exists public.personal_expenses (
  id bigint generated by default as identity primary key,
  owner text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  store_name text,
  amount integer,
  purchase_date date,
  category text,
  receipt_url text
);

create index if not exists personal_expenses_owner_date_idx
  on public.personal_expenses (owner, purchase_date desc);

-- ------------------------------------------------------------
-- 5-2. サブスク（個人）
-- 支払日が来たら、アプリを開いたときに personal_expenses へ自動で記録する。
-- billing_day は最初の支払日の「日」。31日払いが2月に29日などへずれても、翌月は31日に戻すために持つ
-- ------------------------------------------------------------
create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  owner text not null,
  name text not null,
  amount integer not null,
  cycle text not null default 'monthly' check (cycle in ('monthly', 'yearly')),
  billing_day integer not null check (billing_day between 1 and 31),
  next_billing_date date not null,
  category text,
  is_active boolean default true not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists subscriptions_owner_idx
  on public.subscriptions (owner);

-- 自動で記録した支出が、どのサブスクのものか。サブスクを消しても記録は残す
alter table public.personal_expenses
  add column if not exists subscription_id bigint references public.subscriptions (id) on delete set null;

-- 同じサブスクの同じ支払日は1回だけ記録する（2台で同時に開いても二重にならないように）
create unique index if not exists personal_expenses_subscription_date_key
  on public.personal_expenses (subscription_id, purchase_date)
  where subscription_id is not null;

-- ------------------------------------------------------------
-- 6. アクセス制御 (RLS)
--
-- このアプリは Supabase Auth を使わず、ブラウザから anon キーで
-- 直接アクセスする。したがって anon に全操作を許可する必要がある。
-- 裏を返すと、URL と anon キーを知っている人は誰でも読み書きできる。
-- ログイン画面の合言葉は画面を出し分けているだけで、防御にはならない。
-- 将来この前提を変えるときは、ここのポリシーを絞り込む。
-- ------------------------------------------------------------
alter table public.users enable row level security;
alter table public.expenses enable row level security;
alter table public.monthly_settlements enable row level security;
alter table public.trips enable row level security;
alter table public.trip_expenses enable row level security;
alter table public.personal_expenses enable row level security;
alter table public.subscriptions enable row level security;

drop policy if exists "anon full access" on public.users;
create policy "anon full access" on public.users
  for all to anon using (true) with check (true);

drop policy if exists "anon full access" on public.expenses;
create policy "anon full access" on public.expenses
  for all to anon using (true) with check (true);

drop policy if exists "anon full access" on public.monthly_settlements;
create policy "anon full access" on public.monthly_settlements
  for all to anon using (true) with check (true);

drop policy if exists "anon full access" on public.trips;
create policy "anon full access" on public.trips
  for all to anon using (true) with check (true);

drop policy if exists "anon full access" on public.trip_expenses;
create policy "anon full access" on public.trip_expenses
  for all to anon using (true) with check (true);

drop policy if exists "anon full access" on public.personal_expenses;
create policy "anon full access" on public.personal_expenses
  for all to anon using (true) with check (true);

drop policy if exists "anon full access" on public.subscriptions;
create policy "anon full access" on public.subscriptions
  for all to anon using (true) with check (true);

-- ------------------------------------------------------------
-- 7. レシート画像用ストレージ
-- ダッシュボードで手作業で作っても同じ。こちらのほうが取りこぼしがない。
-- ------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('receipts', 'receipts', true)
on conflict (id) do update set public = true;

drop policy if exists "receipts anon read" on storage.objects;
create policy "receipts anon read" on storage.objects
  for select to anon using (bucket_id = 'receipts');

drop policy if exists "receipts anon upload" on storage.objects;
create policy "receipts anon upload" on storage.objects
  for insert to anon with check (bucket_id = 'receipts');

drop policy if exists "receipts anon delete" on storage.objects;
create policy "receipts anon delete" on storage.objects
  for delete to anon using (bucket_id = 'receipts');
